version: '3'
services:
  tdd:
    build: .
    volumes:
    - .:/app
    working_dir: /app
    command: sniffer

  bdd:
    build: .
    volumes:
    - .:/app
    working_dir: /app
    command: behave
